#pragma once

// From glfw3.h
#define V6_MOUSE_BUTTON_1 0
#define V6_MOUSE_BUTTON_2 1
#define V6_MOUSE_BUTTON_3 2
#define V6_MOUSE_BUTTON_4 3
#define V6_MOUSE_BUTTON_5 4
#define V6_MOUSE_BUTTON_6 5
#define V6_MOUSE_BUTTON_7 6
#define V6_MOUSE_BUTTON_8 7
#define V6_MOUSE_BUTTON_LAST V6_MOUSE_BUTTON_8
#define V6_MOUSE_BUTTON_LEFT V6_MOUSE_BUTTON_1
#define V6_MOUSE_BUTTON_RIGHT V6_MOUSE_BUTTON_2
#define V6_MOUSE_BUTTON_MIDDLE V6_MOUSE_BUTTON_3
